version: '3.4'

services:
  panther_gazebo:
    build:
      context: ./../../
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./panther_mecanum.launch:/ros_ws/src/panther_gazebo/launch/panther_mecanum.launch
    command: roslaunch panther_gazebo panther_mecanum.launch