version: "3.4"

services:
  # ROS Galactic simulation
  panther_gazebo:
    image: husarion/panther-gazebo:galactic-latest
    tty: true
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      ros2 launch panther_gazebo panther.launch.py 
      use_gpu:=true

  # ROS Galactic Navigation 2
  nav2:
    image: husarion/nav2:galactic-latest
    tty: true
    restart: on-failure
    depends_on:
      - panther_gazebo
    volumes:
      - ./config/nav2_params.yaml:/app/ros2_ws/src/husarion_nav2/config/nav2_params.yaml
      - ./config/slam_toolbox.yaml:/app/ros2_ws/src/husarion_nav2/config/slam_toolbox.yaml
    command: 
      - sh
      - -c
      - |
        sleep 5
        ros2 launch husarion_nav2 bringup_both.launch.py