version: '3.4'

services:
  panther_gazebo:
    build:
      context: ./../../
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./panther.urdf.xacro:/ros_ws/src/panther_description/urdf/panther.urdf.xacro
      - ./panhter_nvidia.launch:/ros_ws/src/panther_gazebo/launch/panhter_nvidia.launch
    command: roslaunch panther_gazebo panhter_nvidia.launch