version: "3.4"

services:
  panther_gazebo:
    # image: husarion/panther-gazebo:galactic-latest
    build:
      context: ../..
    tty: true
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 launch panther_gazebo panther.launch.py use_gpu:=true