version: '3.4'

services:
  panther_gazebo:
    build:
      context: ./../../
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: roslaunch panther_gazebo panther_rviz.launch