version: '3.4'

services:
  panther_gazebo:
    build:
      context: ../..
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./panther.rviz:/app/ros_ws/src/panther_description/rviz/panther.rviz
      - ./panther.urdf.xacro:/ros_ws/src/panther_description/urdf/panther.urdf.xacro
    command: roslaunch panther_gazebo panther_rviz.launch